# Generated by Django 2.0.1 on 2018-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoex',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
