# Generated by Django 2.0.1 on 2018-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_usergroup_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='uptime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfoex',
            name='test',
            field=models.EmailField(max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='userinfoex',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, '低端用户')], default=1),
        ),
    ]
